kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: jupyterhub-img-wrapper
  namespace: ${NAMESPACE}
  labels:
    app: jupyterhub
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jupyterhub-img:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'jupyterhub-img:latest'
      buildArgs:
      - {"name": "user", "value": "${PROFILES_GIT_USER}"}
      - {"name": "branch", "value": "${PROFILES_GIT_REF}"}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/${WRAPPER_GIT_USER}/jsp-wrapper'
      ref: ${WRAPPER_GIT_REF}
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
status:
  lastVersion: 0
